-- Alpha Gourmet: schema de produção
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text,
  address text,
  city text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  user_id uuid not null references public.profiles(id) on delete restrict,
  plan text not null,
  period text not null,
  plan_quantity integer not null default 1,
  total numeric(12,2) not null,
  payment_method text,
  payment_status text not null default 'pending',
  status text not null default 'received' check (status in ('received','preparing','ready','out_for_delivery','delivered','cancelled')),
  delivery_address text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  meal_id text not null,
  meal_name text not null,
  quantity integer not null check (quantity > 0)
);

create table if not exists public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  note text,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','Cliente Alpha')) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

drop policy if exists "profiles own" on public.profiles;
create policy "profiles own" on public.profiles for select using (auth.uid()=id);

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles for update using (auth.uid()=id);

drop policy if exists "orders own select" on public.orders;
create policy "orders own select" on public.orders for select using (auth.uid()=user_id);

drop policy if exists "orders own insert" on public.orders;
create policy "orders own insert" on public.orders for insert with check (auth.uid()=user_id);

drop policy if exists "items own select" on public.order_items;
create policy "items own select" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));

drop policy if exists "history own select" on public.order_status_history;
create policy "history own select" on public.order_status_history for select using (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
